USE bank_test;

CREATE TABLE IF NOT EXISTS users (
  userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  -- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userID),
  UNIQUE KEY users_username_unique (username)
);

CREATE TABLE IF NOT EXISTS accounts (
  userID INT UNSIGNED NOT NULL,
  accountsID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  amount INT NOT NULL,
  PRIMARY KEY (accountsID)
);

CREATE TABLE IF NOT EXISTS sessions (
  userID INT UNSIGNED NOT NULL,
  token INT UNSIGNED NOT NULL,
  PRIMARY KEY (userID)
);

CREATE TABLE IF NOT EXISTS history (
  transID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  userID INT UNSIGNED NOT NULL,
  transAmount INT UNSIGNED NOT NULL,
  date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (transID)
);